---
title: "Panels Data"
author: "Zein Hasan"
date: "2023-02-15"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Import Library
```{r}
library(psych)
library(tseries)
library(plm)
library(car)
```

## Import data
```{r}
data = read.csv(file.choose())
```

## Check Data
```{r}
head(data)
```
## Check Summary Data
```{r}
summary(data)
```

## Tidy Data
```{r}
data$city=as.factor(data$city)
```

## Make Model
```{r}
# Common Effect Model
ce=plm(rain_sum~daylight_dur+elevation+et0+wd_10m_dom+wg_10m_max+ws_10m_max +snowfall_sum+rain_sum+srs+app_temp_min+app_temp_max+temp_min+temp_max,data,model="pooling",index=c("city","time"))
# Fixed Effect Model
fe=plm(rain_sum~daylight_dur+elevation+et0+wd_10m_dom+wg_10m_max+ws_10m_max +snowfall_sum+rain_sum+srs+app_temp_min+app_temp_max+temp_min+temp_max,data,model="within",index=c("city","time"))
# Random Effect Model
re=plm(rain_sum~daylight_dur+elevation+et0+wd_10m_dom+wg_10m_max+ws_10m_max +snowfall_sum+rain_sum+srs+app_temp_min+app_temp_max+temp_min+temp_max,data,model="random",index=c("city","time"),random.method = "walhus")
```

## Chow Test
```{r}
pooltest(ce,fe)
```
## Hausmann Test
```{r}
phtest(re,fe)
```
## Fixed Effect
## Breusch-Pagan Test
## Uji efek kali silang maupun waktu
```{r}
plmtest(fe,effect="twoways",type="bp") 
```
## Uji efek kali silang
```{r}
plmtest(fe,effect="individual",type="bp")
```
## Uji efek waktu
```{r}
plmtest(fe,effect="time",type="bp")
```




